Repository ministryofjustice/prison-register, pull requests merged in 2024-10, with the labels that each got.

#273 Use Jdk in Docker image + upgrade version of Hmpps orb
  .circleci/config.yml
  Dockerfile
Labels: bug

#278 Renovate some Gradle minor dependencies
  build.gradle.kts
Labels: dependency

#282 Map 1673 add endpoint to return only name given prison
  src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/PrisonResource.kt
  src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/service/PrisonService.kt
  src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/integration/GetPrisonNames.kt
Labels: enhancement

#288 Just like #287 but with only the good bits
  build.gradle.kts
Labels: dependency

#290 minor dependency updates minus Jackson
  build.gradle.kts
Labels: dependency
